function draw_mics_and_floor_in_axes(axes_h,r_mics,r_corners,z)
                            
% Determine axis limits
padding=0.045;  % m, amount of space to add around microphones
xl=[min(r_mics(1,:))-padding max(r_mics(1,:))+padding];
yl=[min(r_mics(2,:))-padding max(r_mics(2,:))+padding];

% set up the main axes
set_axes_size_fixed_center_explicit(axes_h,[w_axes h_axes])
set(axes_h,'box','on', ...
           'visible','off', ...
           'layer','top', ...
           'dataaspectratio',[1 1 1], ...
           'fontsize',7, ...
           'xlim',100*xl, ...
           'ylim',100*yl);

% draw the mask, which covers the part of the density that extends beyond
% the floor outline
r_corners=sortrows(r_corners')';  % make sure sorted by x, then y
r_corners(:,3:4)=fliplr(r_corners(:,3:4));  
  % now they're in clockwise order, starting with the one near the origin
r_mask_part_1= ...
  [xl(1) xl(2) xl(2) xl(1) xl(1) ; ...
   yl(1) yl(1) yl(2) yl(2) yl(1) ];  % outer loop, counterclockwise
r_mask_part_2=[r_corners r_corners(:,1)];  % inner loop, clockwise
r_mask_part_3=[ xl(1) ; ...
                yl(1) ];
r_mask=[r_mask_part_1 r_mask_part_2 r_mask_part_3];
patch('parent',axes_h, ...
      'xdata',100*r_mask(1,:), ...
      'ydata',100*r_mask(2,:), ...
      'zdata',100*repmat(z,[1 size(r_mask,2)]), ...
      'facecolor','w', ...
      'edgecolor','none');
% just to make sure the seam doesn't show
rc=r_corners(:,1);
r_lip=[ xl(1) xl(1) rc(1) rc(1) xl(1) ; ...
        yl(1) rc(2) rc(2) yl(1) yl(1) ];
patch('parent',axes_h, ...
      'xdata',100*r_lip(1,:), ...
      'ydata',100*r_lip(2,:), ...
      'zdata',100*repmat(z,[1 size(r_mask,2)]), ...
      'facecolor','w', ...
      'edgecolor','none');
    
% Draw the microphone symbols and labels
n_mics=size(r_mics,2);
mic_circle_radius=0.02;  % m
for i_mic=1:n_mics
  switch i_mic ,
    case 1,
      v=[0;1];
    case 2,
      v=[1;0];
    case 3,
      v=[0;-1];
    case 4,
      v=[-1;0];
  end
  mic_symbol(axes_h,100*r_mics(1:2,i_mic),v,100*mic_circle_radius, ...
             sprintf('%d',i_mic), ...
             100*z+0.1);
end

% draw the outline of the floor
line('parent',axes_h, ...
     'xdata',100*[r_corners(1,:) r_corners(1,1)], ...
     'ydata',100*[r_corners(2,:) r_corners(2,1)], ...
     'zdata',100*repmat(z,[1 5])+0.1, ...
     'color','k');
   
% draw the scale bar
x=0.4*r_mics(1,1)+0.6*r_mics(1,4);
y=R(2,1)-mic_circle_radius;
line('parent',axes_h, ...
     'xdata',100*x+[-5 5], ...
     'ydata',100*y*[1 1], ...
     'zdata',100*z+0.1, ...
     'color','k', ...
     'linewidth',2);
   
end
