function ...
  place_objective_map_in_axes(axes_h, ...
                              x_grid,y_grid,objective_grid, ...
                              color_function, ...
                              cl, ...
                              title_str, ...
                              clr_mike, ...
                              clr_anno, ...
                              r_est,r_cr, ...
                              R,r_head,r_tail)

%clr_anno=[120 81 169]/255;  % royal purple
if isempty(clr_anno)
  clr_anno=[1 1 1];  % white
end

xl=[x_grid(1,1) x_grid(end,1)];
yl=[y_grid(1,1) y_grid(1,end)];  

fig_h=get(axes_h,'parent');
figure(fig_h);
set(axes_h,'box','on', ...
           'layer','top', ...
           'xlim',1e2*xl, ...
           'ylim',1e2*yl);
if ~isempty(cl)
  set(axes_h,'clim',cl);
end
if ~isempty(objective_grid)
  image('parent',axes_h, ...
        'cdata',objective_grid', ...
        'xdata',1e2*xl, ...
        'ydata',1e2*yl, ...
        'cdatamapping','scaled');
end
colormap(feval(color_function,256));
axis image;
axis xy;
xlabel('x (cm)');
ylabel('y (cm)');
title(title_str,'interpreter','none')

n_mike=size(R,2);
for i=1:n_mike
  line(100*R(1,i),100*R(2,i),0,'marker','.','linestyle','none', ...
       'color',clr_mike(i,:),'markersize',18);       
end
n_mice=size(r_head,2);
line(100*r_head(1,:),100*r_head(2,:),zeros(1,n_mice), ...
     'marker','+','linestyle','none','color',clr_anno, ...
     'markersize',6);
line(100*r_tail(1,:),100*r_tail(2,:),zeros(1,n_mice), ...
     'marker','^','linestyle','none','color',clr_anno, ...
     'markersize',6);     
if ~isempty(r_est)
  line(100*r_est(1),100*r_est(2),zeros(1,n_mice), ...
       'marker','.','linestyle','none','color',clr_anno, ...
       'markersize',6*3);
end
if ~isempty(r_cr)
  if iscell(r_cr)
    % r_cr is a cell array, so draw each element
    n=length(r_cr);
    for i=1:n
      line(100*r_cr{i}(1,:),100*r_cr{i}(2,:),zeros(1,size(r_cr{i},2)), ...
           'marker','none','color',clr_anno);
    end
  else
    % r_cr is not a cell array
    line(100*r_cr(1,:),100*r_cr(2,:),zeros(1,size(r_cr,2)), ...
         'marker','none','color',clr_anno);
  end
end

end
