function [r_est,rsrp_max,rsrp_grid,a,vel,N_filt,V_filt,V,rsrp_per_pair_grid]= ...
  r_est_from_clip_simplified(v,fs, ...
                             f_lo,f_hi, ...
                             Temp, ...
                             x_grid,y_grid,in_cage, ...
                             R, ...
                             verbosity)

% calculate SSE at each grid point                
[rsrp_grid,a,vel,N_filt,V_filt,V,rsrp_per_pair_grid]= ...
  rsrp_grid_from_clip_and_xy_grids(v,fs, ...
                                   f_lo,f_hi, ...
                                   Temp, ...
                                   x_grid,y_grid, ...
                                   R, ...
                                   verbosity);

% find the min-sse point within the cage bounds
%[r_est,sse_min]=argmin_grid(x_grid,y_grid,sse_grid,in_cage);
[r_est,rsrp_max]=argmax_grid(x_grid,y_grid,rsrp_grid);  
  % ignore cage bounds, b/c sometimes they don't help, they hurt

end
