function blobs = ...
  r_est_from_voc_indicators_and_ancillary_for_a_few_vocs(base_dir_name,...
                                                         date_str, ...
                                                         letter_str, ...
                                                         args_common, ...
                                                         argses, ...
                                                         verbosity)

n_vocs=length(argses);
for i=1:n_vocs ,
  args=merge_scalar_structs(args_common,argses(i));
  blob= ...
    r_est_from_voc_indicators_and_ancillary(base_dir_name, ...
                                            date_str, ...
                                            letter_str, ...
                                            args, ...
                                            verbosity);
  % if first iter, dimension blobs                                        
  if i==1 ,
    field_names=fieldnames(blob);
    n_fields=length(field_names);
    keys_and_values=cell(2*n_fields,1);
    keys_and_values(1:2:2*n_fields)=field_names;
    keys_and_values(2:2:2*n_fields)=repmat({cell(n_vocs,1)},[n_fields 1]);
    blobs=struct(keys_and_values{:});
  end
  blobs(i)=blob;
end

end
